sudo: false

language: php

branches:
    only:
        - master

php:
    - 7.0

before_script:
    - composer self-update
    - composer install

script:
  - ./vendor/bin/phpunit --verbose --testsuite=unit